# Generated by Django 2.2.24 on 2023-01-01 11:23

from django.db import migrations


def copy_data_from_Flat_to_Owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flat_objs = Flat.objects.all()
    for flat in flat_objs.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(copy_data_from_Flat_to_Owner)
    ]
