# Generated by Django 2.2.24 on 2023-01-01 15:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230101_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(
                db_index=True,
                related_name='owners',
                to='property.Flat',
                verbose_name='Квартиры в собственности'
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(
                db_index=True,
                max_length=200,
                verbose_name='ФИО владельца'
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, db_index=True,
                max_length=128, null=True,
                region='RU', verbose_name='Нормализованный номер владельца'
            ),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(
                db_index=True,
                max_length=20,
                verbose_name='Номер владельца'
            ),
        ),
    ]
